version: "2.1"
services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      develop:
        ipv4_address: 172.20.10.1

  marine-service-1:
    image: egormit/marine-service
    container_name: marine-service-1
    depends_on:
      - db
      - consul
    environment:
      - DATABASE_HOST=soa-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      develop:
        ipv4_address: 172.20.1.1
    ports:
      - "8000:8000"

  marine-service-2:
    image: egormit/marine-service
    container_name: marine-service-2
    depends_on:
      - db
      - consul
    environment:
      - DATABASE_HOST=soa-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      develop:
        ipv4_address: 172.20.1.2
    ports:
      - "9000:8000"

  starship-service-1:
    image: egormit/starship-service
    container_name: starship-service-1
    depends_on:
      - db
    networks:
      develop:
        ipv4_address: 172.20.1.3
    ports:
      - "8081:8081"

  starship-service-2:
    image: egormit/starship-service
    container_name: starship-service-2
    depends_on:
      - db
    networks:
      develop:
        ipv4_address: 172.20.1.4
    ports:
      - "8082:8081"

  frontend-service:
    image: egormit/frontend-service
    container_name: frontend-service
    volumes:
      - /Projects/WebstormProjects/soa-lab2:/usr/src/app/app
      - /Projects/WebstormProjects/soa-lab2/node_modules
    ports:
      - "8080:8080"
    networks:
      - develop

  db:
    image: postgres
    container_name: soa-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=soa-db
    command: postgres -p 5432
    networks:
      - develop
    ports:
      - "5432:5432"

  haproxy:
    image: "haproxy:2.2-alpine"
    container_name: haproxy
    depends_on:
      - marine-service-1
      - marine-service-2
    ports:
      - "10000:10000"
      - "10100:10100"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - develop

networks:
  develop:
    external:
      name: develop

# Перед запуском создать сеть:
# docker network create develop --subnet=172.20.0.0/16