spring:
  application:
    name: SOA-Lab2-Service2
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/soa-db
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
  sql:
    init:
      platform: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8000